name: Release

on: 
  workflow_dispatch:

jobs:
  release-macosx:
    runs-on: macos-latest
    steps:
      - name: Checkout EzASM
        uses: actions/checkout@v3
        with:
          repository: 'TrevorBrunette/EzASM'
          github-server-url: 'https://github.com'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean package
      - name: Move artifact
        id: stage
        run: |
          ID="EzASM"
          FULL_JAR_NAME="$(basename $(find target -name '*-full.jar'))"
          BASE_NAME="${FULL_JAR_NAME%-full.jar}"
          VERSION="${BASE_NAME#${ID}-}"
          PKG_NAME="${BASE_NAME}-mac.pkg"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "pkg_name=${BASE_NAME}-" >> $GITHUB_OUTPUT
          mkdir staging
          cp "./target/${BASE_NAME}-full.jar" "./staging/${PKG_NAME}"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          release_name: EzASM-${{ steps.stage.outputs.version }}
          tag_name: v${{ steps.stage.outputs.version }}
          files: |
            ./staging/${{ steps.stage.outputs.pkg_name }}
          
